### ISSUE TITLE
[back]アプリ投稿API

### ISSUE THREAD

**Issue by kucyaman** [ikiri-otaku/portfolio_api#57]
機能
- [x] 新規作成
  - [x] GitHubのURL検証処理（アプリのGitHubURLとユーザのGitHubアカウントの正当性チェック）
  - [x] アプリがOrganizationに紐づいている場合、Organizationも登録する？
- [ ] 詳細　※詳細は他のユーザもアクセス可
  - [ ] View数に反映
- [x] 編集　※同Organizationのユーザもアクセス可
- [x] 削除

※アプリ検索は別issue #124

**Comment by m-shiroi** [comment]
新規登録

エンドポイント
`POST   /auth/portfolios`

パラメータ
```
portfolio: {
  name: required, url: required, introduction: optional, github_url: optional
}
```

**Comment by m-shiroi** [comment]
更新

エンドポイント
`PATCH  /auth/portfolios`

パラメータ
```
portfolio: {
  name: required, url: required, introduction: optional, github_url: optional
}
```

**Comment by m-shiroi** [comment]
削除

エンドポイント
`DELETE /auth/portfolios/:id`

パラメータ：なし
