### ISSUE TITLE
[design] アプリカードの種類を整理

### ISSUE THREAD

**Issue by m-shiroi** [ikiri-otaku/portfolio_api#84]
アプリカードの種類が多い

- アイキャッチ、Like＆Watchカウンター）
- タイトル、ブックマーク、技術、ユーザー（アバター＆ユーザー名）、アイキャッチ、Like＆Watchカウンター
  - 高さが半分のパターンあり
  - スマホ向けあり
- タイトル、アプリURL、技術、アイキャッチ、Like＆Watchカウンター）

**Comment by ippei-shimizu** [comment]
@m-shiroi 
このissueってなにをするものでしょうか？

**Comment by m-shiroi** [comment]
> [@m-shiroi](https://github.com/m-shiroi) このissueってなにをするものでしょうか？

@ippei-shimizu 
単純に種類が多すぎるかなーと思ったので、統一できるところは統一したい、というチケットです

**Comment by ippei-shimizu** [comment]
@m-shiroi 
承知いたしました！今って、以下の3種類の認識であっていますか？この3種類でしたらある程度統一されているとは思いますがいかがでしょうか？🤔

- Viewランキング1位とアプリ一覧に使用
[![Image from Gyazo](https://i.gyazo.com/b1b485cac00eec1623f06de38458349e.png)](https://gyazo.com/b1b485cac00eec1623f06de38458349e)

- Viewランキング 2位〜5位に使用
[![Image from Gyazo](https://i.gyazo.com/056a3c8d0857b8c803b53eea4bc1b1ea.png)](https://gyazo.com/056a3c8d0857b8c803b53eea4bc1b1ea)

- 最近の投稿に使用
[![Image from Gyazo](https://i.gyazo.com/1c08f139479c08095d8f938b1e6a17f9.png)](https://gyazo.com/1c08f139479c08095d8f938b1e6a17f9)


これは「Viewランキング 2位〜5位に使用」するコンポーネントのレスポンシブ状態なので新規にコンポーネントは作成しない予定です！
[![Image from Gyazo](https://i.gyazo.com/f2b2de273b336bd26051d50ae62888eb.png)](https://gyazo.com/f2b2de273b336bd26051d50ae62888eb)

**Comment by m-shiroi** [comment]
@ippei-shimizu 
#102 の一番下に貼ったURLつきのもあります！

**Comment by ippei-shimizu** [comment]
こちらに整理しました！
[figma](https://www.figma.com/design/GUuNqXXcPw2Hc0SuT292Cs/ikiri-otaku?node-id=593-5821&t=21KiqXNdrN8nprp1-0)
